site_name: Compatibowl
theme:
  features:
    - navigation.tabs
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: slate
    primary: blue grey
    accent: yellow
markdown_extensions:
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
nav:
- Home: 'index.md'
- Operating Systems:
  - 'android.md'
  - 'macOS.md'
  - 'windows.md'
- Installing Linux Software: 'package-management.md'
- 'installation.md'
repo_url: https://github.com/Champe20/Compatibowl
repo_name: Champe20/Compatibowl